name: Build and Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Label used in zip filename (optional)'
        required: false
        default: 'manual'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        if: github.event_name == 'release'
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Set environment variables (manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV

      - name: Build extension
        run: npm run build

      - name: Zip and rename browser builds (only for release)
        if: github.event_name == 'release'
        run: |
          cd distro
          (cd chrome && zip -r ../chrome.zip .)
          (cd firefox && zip -r ../firefox.zip .)
          cd ..
          mkdir -p packaged
          mv distro/chrome.zip "packaged/${REPO_NAME}-chrome.${RELEASE_TAG}.zip"
          mv distro/firefox.zip "packaged/${REPO_NAME}-firefox.${RELEASE_TAG}.zip"

      - name: Upload zips to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packaged/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Chrome Web Store
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: packaged/${{ env.REPO_NAME }}-chrome.${{ env.RELEASE_TAG }}.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: false
